### ISSUE TITLE
Open Web/Git Server at CampJS

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-iii#14]
It would be useful if we had an open (or semi open) webserver at campjs that people could put their projects on. 

Perhaps hosting a NPM mirror on it would be good too.

**Comment by timoxley** [comment]
We're planning on hosting an npm mirror and having dokku deployed on the network so people can easily get their projects hosted.

**Comment by garrows** [comment]
That's awesome. I was going to mention docker but I haven't tested it out yet. Dokku looks awesome.
