### ISSUE TITLE
the printing on campjs II shirts was terrible

### ISSUE THREAD

**Issue by timoxley** [campjs/campjs-iii#16]
I'm really sorry! Artwork was decent but the way it was printed was an absolute disaster. Let's not do that again.

**Comment by toolmantim** [comment]
I use http://psionline.com.au/ and have done so for the RubyConf tees and many of the Railscamp tees. I order ASColor tees through them, and get discharge ink printing. The end result is top quality, and they last forever. Mary (mary@) is the contact.

**Comment by timoxley** [comment]
Got a better supplier. This should be fixed.
