### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by timoxley** [campjs/campjs-iii#7]
@pomke Can you check my draft code of conduct? 

http://campjs.com/code-of-conduct.html

**Comment by timoxley** [comment]
Any feedback very much appreciated.

**Comment by rvagg** [comment]
needs a link at the bottom to where feedback/improvements can be provided, here I guess.

**Comment by tjstebbing** [comment]
Looks great!

**Comment by SomeoneWeird** [comment]
Needs information about who to contact at the event (@timoxley, other staff members etc).

**Comment by SomeoneWeird** [comment]
Looks good :thumbsup:

**Comment by timoxley** [comment]
Rad :+1:
